global:
  topologyConfig: {}
  imagePullSecrets: []
  imageRegistry: ""
  appName: ""

install: true

appConfig:
  name: sortinghat-worker
  replicas: 1
  image: docker.io/grimoirelab/sortinghat-worker:latest
  pullPolicy: IfNotPresent

  labels: {}
  annotations: {}
  resources:
    cpu:
      limits: ""
      requests: ""
    memory:
      limits: ""
      requests: ""

dependencies:
  storage:
    enabled: false
    volumes: []

service:
  labels: {}
  annotations: {}
  targetPort: 9314
  scheme: "http"
  type: ""  # Default to "ClusterIP"

extraEnvs: []

