---
## Push grimoirelab/* (latest) and grimoirelab/*:tag images,
## for a given item and release.
## item: name of the image (eg. factory, full)
## release: will be used as tag (eg 18.05-02)

- name: "Push grimoirelab/{{item}}:{{RELEASE}}"
  command: "docker push grimoirelab/{{item}}:{{RELEASE}}"

- name: "Push grimoirelab/{{item}}"
  command: "docker push grimoirelab/{{item}}"
