---
## Build and push GrimoireLab Docker images to DockerHub
##
## For this playbook to work, ensure docker-py is Installed
## pip install docker-py
##
## Run as:
## ansible-playbook ansible_release.yml --extra-vars "RELEASE=18.03-04"
## ansible-playbook ansible_release.yml --check --extra-vars "RELEASE=18.04-01" --tags "build"
## ansible-playbook ansible_release.yml --check --extra-vars "RELEASE=latest" --tags "build"
## ansible-playbook ansible_release.yml --check --extra-vars "RELEASE=18.04-01" --tags "push"
##
## Build Python packages and containers, not failing if something goes wrong
## ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook ansible_release.yml --check --extra-vars "RELEASE=18.04-01 fail=" --tags "build"
##
## Variables:
##  - RELEASE: release id (default "latest", other examples: "18.07-11"...)
##  - LOCAL: use repos_local.json to override repos with local ones
##      (default "NO", set as "YES" if using local repos)
##  - FAIL: fail if errors (default "YES", set as "NO" if not to fail)
##
## Tags:
##  - build_pkgs: Build Python packages (and factory container image)
##  - build: Build Python packages and all container images, and run tests
##  - push: Push packages and containers to Pypi and DockerHub
##  - test: Run package tests (assumes container images are available)

- name: Build grimoirelab/factory
  hosts: localhost
  tags:
    - build
  tasks:
    - include_tasks: ansible_build_tag.yml
      loop:
        - factory

- name: Build GrimoireLab packages
  hosts: localhost
  tags:
    - build
    - build_pkgs
  vars:
    RELEASE: "latest"
    LOCAL: "NO"
    FAIL: "YES"
    fail: "{{ ' ' if (FAIL=='NO') else '--fail' }}"
    repos_file: ""
    repo_vol: "{{ playbook_dir }}/..:/grimoirelab"
  tasks:
    - name: "Define local vars if LOCAL"
      set_fact:
        repos_file: "--reposfile /grimoirelab/docker/repos_local.json"
      when: LOCAL == "YES"

    - name: "Create directories for packages and old packages"
      file:
        path: "{{playbook_dir}}/{{item}}"
      with_items:
        - dist
        - dist.old

    - name: "Move old packages from dist to dist.old"
      command: "mv -f {{item}} {{ playbook_dir }}/dist.old"
      with_fileglob:
        "{{playbook_dir}}/dist/*"

    - name: "Build packages using grimoirelab/factory ({{ RELEASE }})"
      when: RELEASE != 'latest'
      docker_container:
        name: factory
        image: "grimoirelab/factory:{{ RELEASE }}"
        volumes:
          - "{{ playbook_dir }}/dist:/dist"
          - "{{ playbook_dir }}/logs:/logs"
          - "{{ playbook_dir }}/../releases/{{ RELEASE }}:/release"
          - "{{repo_vol}}"
        command: "--build --install --check {{ fail }} --relfile /release {{repos_file}}"
        detach: False
      register: result

    - debug:
        msg: "Building output:\n{{result.ansible_facts.docker_container.Output}}"
      when: RELEASE != 'latest' and result.ansible_facts is defined


    - name: "Build packages using grimoirelab/factory (latest in master)"
      when: RELEASE == 'latest'
      docker_container:
        name: factory
        image: "grimoirelab/factory:{{ RELEASE }}"
        volumes:
          - "{{ playbook_dir }}/dist:/dist"
          - "{{ playbook_dir }}/logs:/logs"
        command: "--build --install --check {{ fail }}"
        detach: False
      register: result

    - debug:
        msg: "Building output:\n{{result.ansible_facts.docker_container.Output}}"
      when: RELEASE == 'latest' and result.ansible_facts is defined


- name: "Build grimoirelab/{installed,full}"
  hosts: localhost
  tags:
    - build
  tasks:
    - include_tasks: ansible_build_tag.yml
      loop:
        - installed
        - full

- name: "Test using grimoirelab/full"
  hosts: localhost
  tags:
    - build
    - test
  vars:
    FAIL: "YES"
  tasks:
    - name: "Test using grimoirelab/full:{{RELEASE}}"
      docker_container:
        name: factory
        image: "grimoirelab/full:{{ RELEASE }}"
        volumes:
          - "{{ playbook_dir }}/dist:/dist"
          - "{{ playbook_dir }}/logs:/logs"
          - "{{ playbook_dir }}/testconf:/testconf"
          - "{{ playbook_dir }}/../releases/{{ RELEASE }}:/release"
        env:
          TEST: "YES"
          FAIL: "{{FAIL}}"
        detach: False
      register: result

    - debug:
        msg: "Testing output:\n{{result.ansible_facts.docker_container.Output}}"
      when: result.ansible_facts is defined

- name: "Build grimoirelab/secured"
  hosts: localhost
  tags:
    - build
  tasks:
    - include_tasks: ansible_build_tag.yml
      loop:
        - secured

- name: "Push packages to pypi"
  hosts: localhost
  tags:
    - push
    - push_pypi
  tasks:
    - command: "twine upload --skip-existing {{item}}"
      with_fileglob:
        "{{playbook_dir}}/dist/*"

- name: "Push to DockerHub"
  hosts: localhost
  tags:
    - push
    - push_docker
  tasks:
    - include_tasks: ansible_push.yml
      loop:
        - factory
        - installed
        - full
        - secured
