kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ $.Release.Name }}-configmap"
  labels:
    app: "{{ $.Release.Name }}"

data:
  mordred-setup: |-
    {{- include "config.mordredSetup" . | nindent 4 }}
  mordred-projects: |-
    {{- include "config.mordredProject" . | nindent 4 }}
  uwsgi-params: |-
    {{- include "config.uwsgiParams" . | nindent 4 }}
  nginx-conf-template: |-
    {{- include "config.nginxConf" . | nindent 4 }}
